-- Insert Gallery Images
-- Run this SQL in your Supabase SQL Editor to add gallery items

INSERT INTO gallery (image_url, description, tour_name, tour_id) VALUES
('https://i.ibb.co.com/TD2KcqSd/mark-lawson-6-NUupq-Qej-CE-unsplash-jpg.jpg', 'Golden hour light illuminates the charming streets of historic Lisbon', 'Alfama Walking Tour', NULL),
('https://i.ibb.co.com/yn81YfFd/michiel-annaert-Inx-B1-SWvuw-Q-unsplash-jpg.jpg', 'Traditional Portuguese architecture with azulejo tiles', 'Historic Lisbon', NULL),
('https://i.ibb.co.com/yGBDw8K/pexels-agallego007-15883821-jpg.jpg', 'Vibrant street life in the bustling neighborhoods', 'Downtown Lisbon', NULL),
('https://i.ibb.co.com/twmch9cV/pexels-almir-reis-1982745319-28983214-jpg.jpg', 'Beautiful riverside views along the Tagus', 'Belém', NULL),
('https://i.ibb.co.com/QvNBrx4H/pexels-arathi-m-d-1035706736-20434253-jpg.jpg', 'Colorful facades and local character', 'Alfama Walking Tour', NULL),
('https://i.ibb.co.com/tTR1tN4S/pexels-efrem-efre-2786187-29964340-jpg.jpg', 'Sunset views from the city viewpoints', 'Miradouro Experience', NULL),
('https://i.ibb.co.com/YByXC3jJ/pexels-frankie-hatton-225801-2265922-jpg.jpg', 'Peaceful gardens and green spaces', 'Nature in the City', NULL),
('https://i.ibb.co.com/Y4319JML/pexels-ignacio-pereira-240566698-12304135-jpg.jpg', 'Street art and modern culture', 'Contemporary Lisbon', NULL),
('https://i.ibb.co.com/9mZg07pd/pexels-ignacio-pereira-240566698-12304136-jpg.jpg', 'Urban exploration and hidden gems', 'Off the Beaten Path', NULL),
('https://i.ibb.co.com/bjFTmsD5/pexels-jcosta-11717756-jpg.jpg', 'Local market colors and flavors', 'Food Tour', NULL),
('https://i.ibb.co.com/S7nr16Qx/pexels-joao-aldeia-1232168247-22882475-jpg.jpg', 'Architectural details and craftsmanship', 'Historic Lisbon', NULL),
('https://i.ibb.co.com/9HsPqVzB/pexels-marcos-da-silva-233479891-18546181-jpg.jpg', 'Evening ambiance and Portuguese nightlife', 'Evening Stroll', NULL),
('https://i.ibb.co.com/67zqvPZ0/pexels-mikel-12956566-jpg.jpg', 'Water views and coastal charm', 'Riverside Tour', NULL),
('https://i.ibb.co.com/Mkj6LHSk/pexels-mylokaye-8416035-jpg.jpg', 'Local residents and authentic moments', 'Cultural Encounters', NULL),
('https://i.ibb.co.com/ZRB5XksM/pexels-nbasak-30150460-jpg.jpg', 'Portuguese tile work and traditional crafts', 'Azulejo Heritage', NULL),
('https://i.ibb.co.com/5WBCTwpB/pexels-nuno-magalhaes-1241549-26447919-jpg.jpg', 'Scenic landscapes and panoramic views', 'Viewpoint Explorer', NULL),
('https://i.ibb.co.com/tPkLvwmZ/pexels-taraschuiko-19295416-jpg.jpg', 'Historic monuments and landmarks', 'Historic Lisbon', NULL),
('https://i.ibb.co.com/fV86VPhM/1-angers-city-center-tour-in-an-electric-tuk-tuk-jpg.jpg', 'Unique transportation and city exploration', 'Tuk-Tuk Adventure', NULL),
('https://i.ibb.co.com/mVHR9jx1/719522-3840x2160-desktop-4k-lisbon-portugal-background-photo-jpg.jpg', 'Panoramic cityscape of Lisbon from above', 'City Overview', NULL),
('https://i.ibb.co.com/Tx7q6w6R/719593-2560x1600-desktop-hd-lisbon-portugal-wallpaper-jpg.jpg', 'Iconic Lisbon skyline and landmarks', 'Lisbon Icons', NULL),
('https://i.ibb.co.com/VcHNR88P/20230530-183143-jpg.jpg', 'Guest moment capturing local experience', 'Alfama Walking Tour', NULL),
('https://i.ibb.co.com/Q7ZyK5sG/20231222-102455-jpg.jpg', 'Winter season in Lisbon with festive atmosphere', 'Seasonal Lisbon', NULL),
('https://i.ibb.co.com/rKfTN9rv/20241017-175400-jpg.jpg', 'Autumn colors and street photography', 'Street Stories', NULL),
('https://i.ibb.co.com/S4PXnKTS/alano-oliveira-2-WGg-NKY7-J5-Y-unsplash-jpg.jpg', 'Lisbon neighborhood character and charm', 'Neighborhood Tour', NULL),
('https://i.ibb.co.com/0pfzpQfW/b106516a-362a-4cb0-aead-4415a890d221.jpg', 'Local guide experience and personal connection', 'With Our Guides', NULL),
('https://i.ibb.co.com/6chTNHjN/claudio-schwarz-Iyd-SWl0x-Nfk-unsplash-jpg.jpg', 'Urban exploration and city details', 'Downtown Lisbon', NULL),
('https://i.ibb.co.com/1f3jjTPG/eduardo-goody-0-Iu7m-Ka1s-Pw-unsplash-jpg.jpg', 'Beautiful Lisbon landmarks and viewpoints', 'City Landmarks', NULL),
('https://i.ibb.co.com/kgzDxCq1/filiz-elaerts-J5r-L6a15k-Do-unsplash-jpg.jpg', 'Street life and daily Lisbon moments', 'Local Life', NULL),
('https://i.ibb.co.com/LXLG3xDM/istockphoto-1293307898-1024x1024-jpg.jpg', 'Portuguese architecture and traditional buildings', 'Heritage Tour', NULL),
('https://i.ibb.co.com/nsVSQR9V/jose-maria-sava-mtr8o-Rt-Xjm-M-unsplash-jpg.jpg', 'Lisbon waterfront and river experiences', 'Riverside Tour', NULL),
('https://i.ibb.co.com/jSWzC15/jr-harris-v-P5-Fp-G8-Adz-U-unsplash-jpg.jpg', 'Community and social moments during tours', 'Group Adventures', NULL),
('https://i.ibb.co.com/svr0ny6z/kit-suman-j-Vb-L5jpufcw-unsplash-jpg.jpg', 'Serene and peaceful moments in Lisbon', 'Hidden Tranquility', NULL);
